### ISSUE TITLE
There should be possibility to not specify version for package

### ISSUE THREAD

**Issue by misos1** [joshtriplett/metadeps#13]
Some packages like libjpeg on ubuntu have empty version field:

```
prefix=/usr
exec_prefix=${prefix}
libdir=${prefix}/lib/x86_64-linux-gnu
includedir=${prefix}/include

Name: libjpeg
Description: JPEG image codec
Version: 
Libs: -L${libdir} -ljpeg
Cflags: -I${includedir}
```

It is not possible to use them with metadeps. Whether I specify libjpeg: "0" or libjpeg: "" in cargo.toml it is not working. In pkg-config crate can be version check avoided.

**Comment by joshtriplett** [comment]
This is a distribution bug; please fix the pkg-config file to have a version. The upstream libjpeg project (and the libjpeg-turbo fork) generates a pkg-config file that has a version number.

The point of metadeps is to have declarative dependency information, including versions.

**Comment by misos1** [comment]
But still, for example in cargo.toml one can use "*" to ignore version.

This bug in ubuntu package libjpeg-turbo is here still already few years:
https://bugs.launchpad.net/ubuntu/+source/libjpeg-turbo/+bug/1607696

**Comment by joshtriplett** [comment]
@misos1 
> But still, for example in cargo.toml one can use "*" to ignore version.

Not and upload the crate, though.

> This bug in ubuntu package libjpeg-turbo is here still already few years:

That's unfortunate. Debian's package doesn't seem to have that bug. This is definitely a distribution issue.

You might try escalating that issue to an Ubtuntu support channel. Feel free to CC me and I'd be happy to help.

**Comment by misos1** [comment]
It is already fixed.
